 .sub file Subbasin: 7 8/8/2023 12:00:00 AM ArcSWAT 2012.10_7.23
    17610.840000    | SUB_KM : Subbasin area [km2]

Climate in subbasin
       -8.833552    | LATITUDE : Latitude of subbasin [degrees]
          218.02    | ELEV : Elevation of subbasin [m]
               7    | IRGAGE: precip gage data used in subbasin
               7    | ITGAGE: temp gage data used in subbasin
               0    | ISGAGE: solar radiation gage data used in subbasin
               0    | IHGAGE: relative humidity gage data used in subbasin
               0    | IWGAGE: wind speed gage data used in subbasin
000070000.wgn       | WGNFILE: name of weather generator data file
               1    | FCST_REG: Region number used to assign forecast data to the subbasin
Elevation Bands
| ELEVB: Elevation at center of elevation bands [m]
   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000
| ELEVB_FR: Fraction of subbasin area within elevation band
   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000
| SNOEB: Initial snow water content in elevation band [mm]
     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
           0.000    | PLAPS : Precipitation lapse rate [mm/km]
           0.000    | TLAPS : Temperature lapse rate [°C/km]
           0.000    | SNO_SUB : Initial snow water content [mm]
Tributary Channels
         333.828    | CH_L1 : Longest tributary channel length [km]
           0.001    | CH_S1 : Average slope of tributary channel [m/m]
         455.049    | CH_W1 : Average width of tributary channel [m]
           0.000    | CH_K1 : Effective hydraulic conductivity in tributary channel [mm/hr]
           0.014    | CH_N1 : Manning's "n" value for the tributary channels
Impoundments
000070000.pnd       | PNDFILE: name of subbasin impoundment file
Consumptive Water Use
000070000.wus       | WUSFILE: name of subbasin water use file
Climate Change
         330.000    | CO2 : Carbon dioxide concentration [ppmv]
| RFINC:  Climate change monthly rainfall adjustment (January - June)
   -10.0   -10.0   -10.0   -10.0   -15.0   -20.0
| RFINC:  Climate change monthly rainfall adjustment (July - December)
   -20.0   -20.0   -20.0   -15.0   -10.0   -10.0
| TMPINC: Climate change monthly temperature adjustment (January - June)
   0.000   0.000   0.000   0.000   0.000   0.000
| TMPINC: Climate change monthly temperature adjustment (July - December)
   0.000   0.000   0.000   0.000   0.000   0.000
| RADINC: Climate change monthly radiation adjustment (January - June)
   0.000   0.000   0.000   0.000   0.000   0.000
| RADINC: Climate change monthly radiation adjustment (July - December)
   0.000   0.000   0.000   0.000   0.000   0.000
| HUMINC: Climate change monthly humidity adjustment (January - June)
   0.000   0.000   0.000   0.000   0.000   0.000
| HUMINC: Climate change monthly humidity adjustment (July - December)
   0.000   0.000   0.000   0.000   0.000   0.000
| HRU data
               6    | HRUTOT : Total number of HRUs modeled in subbasin

HRU: Depressional Storage/Pothole

Floodplain

HRU: Riparian

HRU: General
000070001.hru000070001.mgt000070001.sol000070001.chm 000070001.gw             000070001.sep
000070002.hru000070002.mgt000070002.sol000070002.chm 000070002.gw             000070002.sep
000070003.hru000070003.mgt000070003.sol000070003.chm 000070003.gw             000070003.sep
000070004.hru000070004.mgt000070004.sol000070004.chm 000070004.gw             000070004.sep
000070005.hru000070005.mgt000070005.sol000070005.chm 000070005.gw             000070005.sep
000070006.hru000070006.mgt000070006.sol000070006.chm 000070006.gw             000070006.sep
