 .sub file Subbasin: 5 8/8/2023 12:00:00 AM ArcSWAT 2012.10_7.23
    21131.460000    | SUB_KM : Subbasin area [km2]

Climate in subbasin
      -10.000245    | LATITUDE : Latitude of subbasin [degrees]
          448.51    | ELEV : Elevation of subbasin [m]
               5    | IRGAGE: precip gage data used in subbasin
               5    | ITGAGE: temp gage data used in subbasin
               0    | ISGAGE: solar radiation gage data used in subbasin
               0    | IHGAGE: relative humidity gage data used in subbasin
               0    | IWGAGE: wind speed gage data used in subbasin
000050000.wgn       | WGNFILE: name of weather generator data file
               1    | FCST_REG: Region number used to assign forecast data to the subbasin
Elevation Bands
| ELEVB: Elevation at center of elevation bands [m]
   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000
| ELEVB_FR: Fraction of subbasin area within elevation band
   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000
| SNOEB: Initial snow water content in elevation band [mm]
     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
           0.000    | PLAPS : Precipitation lapse rate [mm/km]
           0.000    | TLAPS : Temperature lapse rate [°C/km]
           0.000    | SNO_SUB : Initial snow water content [mm]
Tributary Channels
         502.062    | CH_L1 : Longest tributary channel length [km]
           0.004    | CH_S1 : Average slope of tributary channel [m/m]
         507.630    | CH_W1 : Average width of tributary channel [m]
           0.000    | CH_K1 : Effective hydraulic conductivity in tributary channel [mm/hr]
           0.014    | CH_N1 : Manning's "n" value for the tributary channels
Impoundments
000050000.pnd       | PNDFILE: name of subbasin impoundment file
Consumptive Water Use
000050000.wus       | WUSFILE: name of subbasin water use file
Climate Change
         330.000    | CO2 : Carbon dioxide concentration [ppmv]
| RFINC:  Climate change monthly rainfall adjustment (January - June)
   -10.0   -10.0   -10.0   -10.0   -15.0   -20.0
| RFINC:  Climate change monthly rainfall adjustment (July - December)
   -20.0   -20.0   -20.0   -15.0   -10.0   -10.0
| TMPINC: Climate change monthly temperature adjustment (January - June)
   0.000   0.000   0.000   0.000   0.000   0.000
| TMPINC: Climate change monthly temperature adjustment (July - December)
   0.000   0.000   0.000   0.000   0.000   0.000
| RADINC: Climate change monthly radiation adjustment (January - June)
   0.000   0.000   0.000   0.000   0.000   0.000
| RADINC: Climate change monthly radiation adjustment (July - December)
   0.000   0.000   0.000   0.000   0.000   0.000
| HUMINC: Climate change monthly humidity adjustment (January - June)
   0.000   0.000   0.000   0.000   0.000   0.000
| HUMINC: Climate change monthly humidity adjustment (July - December)
   0.000   0.000   0.000   0.000   0.000   0.000
| HRU data
               8    | HRUTOT : Total number of HRUs modeled in subbasin

HRU: Depressional Storage/Pothole

Floodplain

HRU: Riparian

HRU: General
000050001.hru000050001.mgt000050001.sol000050001.chm 000050001.gw             000050001.sep
000050002.hru000050002.mgt000050002.sol000050002.chm 000050002.gw             000050002.sep
000050003.hru000050003.mgt000050003.sol000050003.chm 000050003.gw             000050003.sep
000050004.hru000050004.mgt000050004.sol000050004.chm 000050004.gw             000050004.sep
000050005.hru000050005.mgt000050005.sol000050005.chm 000050005.gw             000050005.sep
000050006.hru000050006.mgt000050006.sol000050006.chm 000050006.gw             000050006.sep
000050007.hru000050007.mgt000050007.sol000050007.chm 000050007.gw             000050007.sep
000050008.hru000050008.mgt000050008.sol000050008.chm 000050008.gw             000050008.sep
