 .sub file Subbasin: 2 8/8/2023 12:00:00 AM ArcSWAT 2012.10_7.23
     7547.490000    | SUB_KM : Subbasin area [km2]

Climate in subbasin
       -6.024229    | LATITUDE : Latitude of subbasin [degrees]
          143.59    | ELEV : Elevation of subbasin [m]
               2    | IRGAGE: precip gage data used in subbasin
               2    | ITGAGE: temp gage data used in subbasin
               0    | ISGAGE: solar radiation gage data used in subbasin
               0    | IHGAGE: relative humidity gage data used in subbasin
               0    | IWGAGE: wind speed gage data used in subbasin
000020000.wgn       | WGNFILE: name of weather generator data file
               1    | FCST_REG: Region number used to assign forecast data to the subbasin
Elevation Bands
| ELEVB: Elevation at center of elevation bands [m]
   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000
| ELEVB_FR: Fraction of subbasin area within elevation band
   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000
| SNOEB: Initial snow water content in elevation band [mm]
     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
           0.000    | PLAPS : Precipitation lapse rate [mm/km]
           0.000    | TLAPS : Temperature lapse rate [°C/km]
           0.000    | SNO_SUB : Initial snow water content [mm]
Tributary Channels
         314.858    | CH_L1 : Longest tributary channel length [km]
           0.002    | CH_S1 : Average slope of tributary channel [m/m]
         273.698    | CH_W1 : Average width of tributary channel [m]
           0.000    | CH_K1 : Effective hydraulic conductivity in tributary channel [mm/hr]
           0.014    | CH_N1 : Manning's "n" value for the tributary channels
Impoundments
000020000.pnd       | PNDFILE: name of subbasin impoundment file
Consumptive Water Use
000020000.wus       | WUSFILE: name of subbasin water use file
Climate Change
         330.000    | CO2 : Carbon dioxide concentration [ppmv]
 RFINC:  Climate change monthly rainfall adjustment (January - June)
   -10.0   -20.0   -30.0   -20.0    10.0   60.00
| RFINC:  Climate change monthly rainfall adjustment (July - December)
   50.00   40.00   30.00   30.00   20.00   20.00
| TMPINC: Climate change monthly temperature adjustment (January - June)
   0.000   0.000   0.000   0.000   0.000   0.000
| TMPINC: Climate change monthly temperature adjustment (July - December)
   0.000   0.000   0.000   0.000   0.000   0.000
| RADINC: Climate change monthly radiation adjustment (January - June)
   0.000   0.000   0.000   0.000   0.000   0.000
| RADINC: Climate change monthly radiation adjustment (July - December)
   0.000   0.000   0.000   0.000   0.000   0.000
| HUMINC: Climate change monthly humidity adjustment (January - June)
   0.000   0.000   0.000   0.000   0.000   0.000
| HUMINC: Climate change monthly humidity adjustment (July - December)
   0.000   0.000   0.000   0.000   0.000   0.000
| HRU data
               6    | HRUTOT : Total number of HRUs modeled in subbasin

HRU: Depressional Storage/Pothole

Floodplain

HRU: Riparian

HRU: General
000020001.hru000020001.mgt000020001.sol000020001.chm 000020001.gw             000020001.sep
000020002.hru000020002.mgt000020002.sol000020002.chm 000020002.gw             000020002.sep
000020003.hru000020003.mgt000020003.sol000020003.chm 000020003.gw             000020003.sep
000020004.hru000020004.mgt000020004.sol000020004.chm 000020004.gw             000020004.sep
000020005.hru000020005.mgt000020005.sol000020005.chm 000020005.gw             000020005.sep
000020006.hru000020006.mgt000020006.sol000020006.chm 000020006.gw             000020006.sep
