 .sub file Subbasin: 3 8/8/2023 12:00:00 AM ArcSWAT 2012.10_7.23
     7105.770000    | SUB_KM : Subbasin area [km2]

Climate in subbasin
       -7.297216    | LATITUDE : Latitude of subbasin [degrees]
          543.93    | ELEV : Elevation of subbasin [m]
               3    | IRGAGE: precip gage data used in subbasin
               3    | ITGAGE: temp gage data used in subbasin
               0    | ISGAGE: solar radiation gage data used in subbasin
               0    | IHGAGE: relative humidity gage data used in subbasin
               0    | IWGAGE: wind speed gage data used in subbasin
000030000.wgn       | WGNFILE: name of weather generator data file
               1    | FCST_REG: Region number used to assign forecast data to the subbasin
Elevation Bands
| ELEVB: Elevation at center of elevation bands [m]
   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000
| ELEVB_FR: Fraction of subbasin area within elevation band
   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000
| SNOEB: Initial snow water content in elevation band [mm]
     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
           0.000    | PLAPS : Precipitation lapse rate [mm/km]
           0.000    | TLAPS : Temperature lapse rate [°C/km]
           0.000    | SNO_SUB : Initial snow water content [mm]
Tributary Channels
         236.861    | CH_L1 : Longest tributary channel length [km]
           0.004    | CH_S1 : Average slope of tributary channel [m/m]
         263.971    | CH_W1 : Average width of tributary channel [m]
           0.000    | CH_K1 : Effective hydraulic conductivity in tributary channel [mm/hr]
           0.014    | CH_N1 : Manning's "n" value for the tributary channels
Impoundments
000030000.pnd       | PNDFILE: name of subbasin impoundment file
Consumptive Water Use
000030000.wus       | WUSFILE: name of subbasin water use file
Climate Change
         330.000    | CO2 : Carbon dioxide concentration [ppmv]
 RFINC:  Climate change monthly rainfall adjustment (January - June)
   -10.0   -20.0   -30.0   -20.0    10.0   60.00
| RFINC:  Climate change monthly rainfall adjustment (July - December)
   50.00   40.00   30.00   30.00   20.00   20.00
| TMPINC: Climate change monthly temperature adjustment (January - June)
   0.000   0.000   0.000   0.000   0.000   0.000
| TMPINC: Climate change monthly temperature adjustment (July - December)
   0.000   0.000   0.000   0.000   0.000   0.000
| RADINC: Climate change monthly radiation adjustment (January - June)
   0.000   0.000   0.000   0.000   0.000   0.000
| RADINC: Climate change monthly radiation adjustment (July - December)
   0.000   0.000   0.000   0.000   0.000   0.000
| HUMINC: Climate change monthly humidity adjustment (January - June)
   0.000   0.000   0.000   0.000   0.000   0.000
| HUMINC: Climate change monthly humidity adjustment (July - December)
   0.000   0.000   0.000   0.000   0.000   0.000
| HRU data
               7    | HRUTOT : Total number of HRUs modeled in subbasin

HRU: Depressional Storage/Pothole

Floodplain

HRU: Riparian

HRU: General
000030001.hru000030001.mgt000030001.sol000030001.chm 000030001.gw             000030001.sep
000030002.hru000030002.mgt000030002.sol000030002.chm 000030002.gw             000030002.sep
000030003.hru000030003.mgt000030003.sol000030003.chm 000030003.gw             000030003.sep
000030004.hru000030004.mgt000030004.sol000030004.chm 000030004.gw             000030004.sep
000030005.hru000030005.mgt000030005.sol000030005.chm 000030005.gw             000030005.sep
000030006.hru000030006.mgt000030006.sol000030006.chm 000030006.gw             000030006.sep
000030007.hru000030007.mgt000030007.sol000030007.chm 000030007.gw             000030007.sep
