 .sub file Subbasin: 19 8/8/2023 12:00:00 AM ArcSWAT 2012.10_7.23
    35573.940000    | SUB_KM : Subbasin area [km2]

Climate in subbasin
      -10.652056    | LATITUDE : Latitude of subbasin [degrees]
          661.39    | ELEV : Elevation of subbasin [m]
              19    | IRGAGE: precip gage data used in subbasin
              19    | ITGAGE: temp gage data used in subbasin
               0    | ISGAGE: solar radiation gage data used in subbasin
               0    | IHGAGE: relative humidity gage data used in subbasin
               0    | IWGAGE: wind speed gage data used in subbasin
000190000.wgn       | WGNFILE: name of weather generator data file
               1    | FCST_REG: Region number used to assign forecast data to the subbasin
Elevation Bands
| ELEVB: Elevation at center of elevation bands [m]
   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000
| ELEVB_FR: Fraction of subbasin area within elevation band
   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000
| SNOEB: Initial snow water content in elevation band [mm]
     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
           0.000    | PLAPS : Precipitation lapse rate [mm/km]
           0.000    | TLAPS : Temperature lapse rate [°C/km]
           0.000    | SNO_SUB : Initial snow water content [mm]
Tributary Channels
         432.916    | CH_L1 : Longest tributary channel length [km]
           0.008    | CH_S1 : Average slope of tributary channel [m/m]
         693.855    | CH_W1 : Average width of tributary channel [m]
           0.000    | CH_K1 : Effective hydraulic conductivity in tributary channel [mm/hr]
           0.014    | CH_N1 : Manning's "n" value for the tributary channels
Impoundments
000190000.pnd       | PNDFILE: name of subbasin impoundment file
Consumptive Water Use
000190000.wus       | WUSFILE: name of subbasin water use file
Climate Change
         330.000    | CO2 : Carbon dioxide concentration [ppmv]
| RFINC:  Climate change monthly rainfall adjustment (January - June)
   -10.0   -10.0   -10.0   -10.0   -15.0   -20.0
| RFINC:  Climate change monthly rainfall adjustment (July - December)
   -20.0   -20.0   -20.0   -15.0   -10.0   -10.0
| TMPINC: Climate change monthly temperature adjustment (January - June)
   0.000   0.000   0.000   0.000   0.000   0.000
| TMPINC: Climate change monthly temperature adjustment (July - December)
   0.000   0.000   0.000   0.000   0.000   0.000
| RADINC: Climate change monthly radiation adjustment (January - June)
   0.000   0.000   0.000   0.000   0.000   0.000
| RADINC: Climate change monthly radiation adjustment (July - December)
   0.000   0.000   0.000   0.000   0.000   0.000
| HUMINC: Climate change monthly humidity adjustment (January - June)
   0.000   0.000   0.000   0.000   0.000   0.000
| HUMINC: Climate change monthly humidity adjustment (July - December)
   0.000   0.000   0.000   0.000   0.000   0.000
| HRU data
               4    | HRUTOT : Total number of HRUs modeled in subbasin

HRU: Depressional Storage/Pothole

Floodplain

HRU: Riparian

HRU: General
000190001.hru000190001.mgt000190001.sol000190001.chm 000190001.gw             000190001.sep
000190002.hru000190002.mgt000190002.sol000190002.chm 000190002.gw             000190002.sep
000190003.hru000190003.mgt000190003.sol000190003.chm 000190003.gw             000190003.sep
000190004.hru000190004.mgt000190004.sol000190004.chm 000190004.gw             000190004.sep
