 .sub file Subbasin: 18 8/8/2023 12:00:00 AM ArcSWAT 2012.10_7.23
    16872.840000    | SUB_KM : Subbasin area [km2]

Climate in subbasin
      -11.830152    | LATITUDE : Latitude of subbasin [degrees]
         1833.86    | ELEV : Elevation of subbasin [m]
              18    | IRGAGE: precip gage data used in subbasin
              18    | ITGAGE: temp gage data used in subbasin
               0    | ISGAGE: solar radiation gage data used in subbasin
               0    | IHGAGE: relative humidity gage data used in subbasin
               0    | IWGAGE: wind speed gage data used in subbasin
000180000.wgn       | WGNFILE: name of weather generator data file
               1    | FCST_REG: Region number used to assign forecast data to the subbasin
Elevation Bands
| ELEVB: Elevation at center of elevation bands [m]
   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000
| ELEVB_FR: Fraction of subbasin area within elevation band
   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000
| SNOEB: Initial snow water content in elevation band [mm]
     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
           0.000    | PLAPS : Precipitation lapse rate [mm/km]
           0.000    | TLAPS : Temperature lapse rate [°C/km]
           0.000    | SNO_SUB : Initial snow water content [mm]
Tributary Channels
         220.258    | CH_L1 : Longest tributary channel length [km]
           0.017    | CH_S1 : Average slope of tributary channel [m/m]
         443.509    | CH_W1 : Average width of tributary channel [m]
           0.000    | CH_K1 : Effective hydraulic conductivity in tributary channel [mm/hr]
           0.014    | CH_N1 : Manning's "n" value for the tributary channels
Impoundments
000180000.pnd       | PNDFILE: name of subbasin impoundment file
Consumptive Water Use
000180000.wus       | WUSFILE: name of subbasin water use file
Climate Change
         330.000    | CO2 : Carbon dioxide concentration [ppmv]
| RFINC:  Climate change monthly rainfall adjustment (January - June)
   20.00   20.00   20.00   15.00   10.00   10.00
| RFINC:  Climate change monthly rainfall adjustment (July - December)
   10.00   10.00   10.00   10.00   20.00   20.00
| TMPINC: Climate change monthly temperature adjustment (January - June)
   0.000   0.000   0.000   0.000   0.000   0.000
| TMPINC: Climate change monthly temperature adjustment (July - December)
   0.000   0.000   0.000   0.000   0.000   0.000
| RADINC: Climate change monthly radiation adjustment (January - June)
   0.000   0.000   0.000   0.000   0.000   0.000
| RADINC: Climate change monthly radiation adjustment (July - December)
   0.000   0.000   0.000   0.000   0.000   0.000
| HUMINC: Climate change monthly humidity adjustment (January - June)
   0.000   0.000   0.000   0.000   0.000   0.000
| HUMINC: Climate change monthly humidity adjustment (July - December)
   0.000   0.000   0.000   0.000   0.000   0.000
| HRU data
               4    | HRUTOT : Total number of HRUs modeled in subbasin

HRU: Depressional Storage/Pothole

Floodplain

HRU: Riparian

HRU: General
000180001.hru000180001.mgt000180001.sol000180001.chm 000180001.gw             000180001.sep
000180002.hru000180002.mgt000180002.sol000180002.chm 000180002.gw             000180002.sep
000180003.hru000180003.mgt000180003.sol000180003.chm 000180003.gw             000180003.sep
000180004.hru000180004.mgt000180004.sol000180004.chm 000180004.gw             000180004.sep
