 .sub file Subbasin: 23 8/8/2023 12:00:00 AM ArcSWAT 2012.10_7.23
    13922.730000    | SUB_KM : Subbasin area [km2]

Climate in subbasin
       -7.458243    | LATITUDE : Latitude of subbasin [degrees]
          193.39    | ELEV : Elevation of subbasin [m]
              23    | IRGAGE: precip gage data used in subbasin
              23    | ITGAGE: temp gage data used in subbasin
               0    | ISGAGE: solar radiation gage data used in subbasin
               0    | IHGAGE: relative humidity gage data used in subbasin
               0    | IWGAGE: wind speed gage data used in subbasin
000230000.wgn       | WGNFILE: name of weather generator data file
               1    | FCST_REG: Region number used to assign forecast data to the subbasin
Elevation Bands
| ELEVB: Elevation at center of elevation bands [m]
   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000
| ELEVB_FR: Fraction of subbasin area within elevation band
   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000
| SNOEB: Initial snow water content in elevation band [mm]
     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
           0.000    | PLAPS : Precipitation lapse rate [mm/km]
           0.000    | TLAPS : Temperature lapse rate [°C/km]
           0.000    | SNO_SUB : Initial snow water content [mm]
Tributary Channels
         219.997    | CH_L1 : Longest tributary channel length [km]
           0.001    | CH_S1 : Average slope of tributary channel [m/m]
         395.207    | CH_W1 : Average width of tributary channel [m]
           0.000    | CH_K1 : Effective hydraulic conductivity in tributary channel [mm/hr]
           0.014    | CH_N1 : Manning's "n" value for the tributary channels
Impoundments
000230000.pnd       | PNDFILE: name of subbasin impoundment file
Consumptive Water Use
000230000.wus       | WUSFILE: name of subbasin water use file
Climate Change
         330.000    | CO2 : Carbon dioxide concentration [ppmv]
 RFINC:  Climate change monthly rainfall adjustment (January - June)
   0.00    -10.0   -10.0   -10.0   60.00   90.00
| RFINC:  Climate change monthly rainfall adjustment (July - December)
   50.00   40.00   30.00   30.00   0.000   -10.0
| TMPINC: Climate change monthly temperature adjustment (January - June)
   0.000   0.000   0.000   0.000   0.000   0.000
| TMPINC: Climate change monthly temperature adjustment (July - December)
   0.000   0.000   0.000   0.000   0.000   0.000
| RADINC: Climate change monthly radiation adjustment (January - June)
   0.000   0.000   0.000   0.000   0.000   0.000
| RADINC: Climate change monthly radiation adjustment (July - December)
   0.000   0.000   0.000   0.000   0.000   0.000
| HUMINC: Climate change monthly humidity adjustment (January - June)
   0.000   0.000   0.000   0.000   0.000   0.000
| HUMINC: Climate change monthly humidity adjustment (July - December)
   0.000   0.000   0.000   0.000   0.000   0.000
| HRU data
               3    | HRUTOT : Total number of HRUs modeled in subbasin

HRU: Depressional Storage/Pothole

Floodplain

HRU: Riparian

HRU: General
000230001.hru000230001.mgt000230001.sol000230001.chm 000230001.gw             000230001.sep
000230002.hru000230002.mgt000230002.sol000230002.chm 000230002.gw             000230002.sep
000230003.hru000230003.mgt000230003.sol000230003.chm 000230003.gw             000230003.sep
