 .sub file Subbasin: 20 8/8/2023 12:00:00 AM ArcSWAT 2012.10_7.23
    12339.270000    | SUB_KM : Subbasin area [km2]

Climate in subbasin
       -9.633096    | LATITUDE : Latitude of subbasin [degrees]
          727.81    | ELEV : Elevation of subbasin [m]
              20    | IRGAGE: precip gage data used in subbasin
              20    | ITGAGE: temp gage data used in subbasin
               0    | ISGAGE: solar radiation gage data used in subbasin
               0    | IHGAGE: relative humidity gage data used in subbasin
               0    | IWGAGE: wind speed gage data used in subbasin
000200000.wgn       | WGNFILE: name of weather generator data file
               1    | FCST_REG: Region number used to assign forecast data to the subbasin
Elevation Bands
| ELEVB: Elevation at center of elevation bands [m]
   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000
| ELEVB_FR: Fraction of subbasin area within elevation band
   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000   0.000
| SNOEB: Initial snow water content in elevation band [mm]
     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
           0.000    | PLAPS : Precipitation lapse rate [mm/km]
           0.000    | TLAPS : Temperature lapse rate [°C/km]
           0.000    | SNO_SUB : Initial snow water content [mm]
Tributary Channels
         269.127    | CH_L1 : Longest tributary channel length [km]
           0.006    | CH_S1 : Average slope of tributary channel [m/m]
         367.590    | CH_W1 : Average width of tributary channel [m]
           0.000    | CH_K1 : Effective hydraulic conductivity in tributary channel [mm/hr]
           0.014    | CH_N1 : Manning's "n" value for the tributary channels
Impoundments
000200000.pnd       | PNDFILE: name of subbasin impoundment file
Consumptive Water Use
000200000.wus       | WUSFILE: name of subbasin water use file
Climate Change
         330.000    | CO2 : Carbon dioxide concentration [ppmv]
| RFINC:  Climate change monthly rainfall adjustment (January - June)
   35.00   35.00   20.00   10.00   10.00   10.00
| RFINC:  Climate change monthly rainfall adjustment (July - December)
   10.00   10.00   10.00   10.00   20.00   35.00
| TMPINC: Climate change monthly temperature adjustment (January - June)
   0.000   0.000   0.000   0.000   0.000   0.000
| TMPINC: Climate change monthly temperature adjustment (July - December)
   0.000   0.000   0.000   0.000   0.000   0.000
| RADINC: Climate change monthly radiation adjustment (January - June)
   0.000   0.000   0.000   0.000   0.000   0.000
| RADINC: Climate change monthly radiation adjustment (July - December)
   0.000   0.000   0.000   0.000   0.000   0.000
| HUMINC: Climate change monthly humidity adjustment (January - June)
   0.000   0.000   0.000   0.000   0.000   0.000
| HUMINC: Climate change monthly humidity adjustment (July - December)
   0.000   0.000   0.000   0.000   0.000   0.000
| HRU data
               4    | HRUTOT : Total number of HRUs modeled in subbasin

HRU: Depressional Storage/Pothole

Floodplain

HRU: Riparian

HRU: General
000200001.hru000200001.mgt000200001.sol000200001.chm 000200001.gw             000200001.sep
000200002.hru000200002.mgt000200002.sol000200002.chm 000200002.gw             000200002.sep
000200003.hru000200003.mgt000200003.sol000200003.chm 000200003.gw             000200003.sep
000200004.hru000200004.mgt000200004.sol000200004.chm 000200004.gw             000200004.sep
